server:
  port: 8081

spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
        strategy: refresh
        mode: event
      config:
        enabled: true
        name: java-config
        namespace: ${POD_NAMESPACE:config-hot-reload}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
