apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hot-reload
  namespace: config-hot-reload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-hot-reload
  template:
    metadata:
      labels:
        app: java-hot-reload
    spec:
      serviceAccountName: java-hot-reload-sa
      containers:
        - name: java-hot-reload
          image: local/java-hot-reload:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: java-hot-reload-svc
  namespace: config-hot-reload
spec:
  selector:
    app: java-hot-reload
  ports:
    - port: 80
      targetPort: 8081
