apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-hot-reload-sa
  namespace: config-hot-reload
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: java-hot-reload-role
  namespace: config-hot-reload
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-hot-reload-rb
  namespace: config-hot-reload
subjects:
  - kind: ServiceAccount
    name: java-hot-reload-sa
roleRef:
  kind: Role
  name: java-hot-reload-role
  apiGroup: rbac.authorization.k8s.io
